### ISSUE TITLE
Add some examples in the documentation

### ISSUE THREAD

**Issue by ytdHuang** [NCKU-QFort/HierarchicalEOM.jl#13]
We should add some more simple examples in the documentation

**Comment by ytdHuang** [comment]
Add Example: single-impurity Anderson model (https://github.com/NCKU-QFort/HierarchicalEOM.jl/commit/afc6c0dbe012d7f108d02577a092b24737a71862)

**Comment by ytdHuang** [comment]
Add Example: Driven systems and dynamical decoupling (https://github.com/NCKU-QFort/HierarchicalEOM.jl/commit/deea08ab092ee3be66cb9d0511a4ec587985ef08)

**Comment by qazwsx351789** [comment]
Add Example : Cavity QED (https://github.com/NCKU-QFort/HierarchicalEOM.jl/commit/2cc36abaf1fc8454ba0dc2f7e42a7087a3b814c4)

**Comment by ytdHuang** [comment]
#16
